# Page settings

baseURL = "https://www.sharadvernekar.com/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Sharad Vernekar"
        tagline = "eCommerce Application Architect"
        avatar = "avatar1.png"

    [params.contact]
        enable = true
        location = "Plano"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "214 425 7589"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "sharad.vernekar@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.sharadvernekar.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JAVA/SpringBoot/REST"
        [[params.skills.list.items]]
        details = "JavaScript/Angular"
        [[params.skills.list.items]]
        details = "Magento/PHP"
        [[params.skills.list.items]]
        details = "Pivotal Cloud Foundry/Adobe Cloud"
        [[params.skills.list.items]]
        details = "Jenkins/GitLab"
        [[params.skills.list.items]]
        details = "Oracle/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Excellent time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MBA in Finance"
        university = "University of Texas, Dallas Texas"
        dates = "2005 - 2007"
        [[params.education.list]]
        degree = "BE in Computer Technologu"
        university = "Victoria Jubilee Technical Institute (VJTI), Bombay India"
        dates = "1990 - 1994"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "FedEx IT Hall of Fame Award"
        body = "FedEx Office Data Center Consolidation project"
        date = "FY2021 Q1"
        [[params.awards.list]]
        name = "FedEx Purple Star Award"
        body = "Migration to PCF"
        date = "FY2021 Q2"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Hindi"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Chess"
        [[params.interests.list]]
        name = "Skiing"
        [[params.interests.list]]
        name = "Swimming"
        [[params.interests.list]]
        name = "Gardening"
        [[params.interests.list]]
        name = "Photography"

    [params.summary]
        enable = true
        text = "Software professional with over 25 years of experience in software delivery. My experience includes design and development of cutting-edge responsive web applications and RESTful web services using Angular framework for user interface and Spring Boot framework for microservice development. I demonstrate technical leadership; solve analytical problem and focus on long term objectives while delivering short term goals. I have the ability to take risks, develop quality solutions, and automate processes to drive cost reduction. I have exceptional organization skills with the ability to multitask and develop strong work relationships. I have successfully implemented several projects from concept to implementation using Agile methodologies, SCRUM framework, Continuous Integration (CI) and Continuous Delivery (CD) concepts. I am also a Certified USA Swimming official."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "eCommerce Architect"
        dates = "2020 - Present"
        company = "FedEx Corporation"
        details = "Architect for the FedEx Office Print online applications. Design and develop processes on the new Magento eCommerce platform. FedEx Office is migrating its Angular based eCommerce solution to the Magento framework based solution hosted in Adobe Cloud. "
        [[params.experience.list.items]]
        details = "Identify and define the APIs needed to support the new platform."
        [[params.experience.list.items]]
        details = "Set up tools and processes on Magento cloud."
        [[params.experience.list.items]]
        details = "Assist product owners define requirements and acceptance criteria."

        [[params.experience.list]]
        title = "Full Stack Developer Advisor"
        dates = "2016 - 2019"
        company = "FedEx Corporation"
        details = "Full Stack Developer Advisor for the FedEx Office eCommerce Value Stream organization. Technical owner and lead for several micro services and web components of the FedEx Office printing solutions eCommerce application flow."
        [[params.experience.list.items]]
        details = "Build SOAP based MVC web services."
        [[params.experience.list.items]]
        details = "Design and build Spring boot microservices and deploy them to PCF cloud."
        [[params.experience.list.items]]
        details = "Build Angular web application for FedEx Office print solution."
        [[params.experience.list.items]]
        details = "Set up AppDynamics monitoring for PCF applications."
        [[params.experience.list.items]]
        details = "Configure Jenkins CI/CD pipeline for full automation of code deployment and release management."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2012 - 2016"
        company = "FedEx Corporation"
        details = "Code development and testing of FedEx Office applications supporting."
        [[params.experience.list.items]]
        details = "Migrated several legacy applications to SOAP based Spring applications."
        [[params.experience.list.items]]
        details = "Built and integrated tax system based on Vertex solution to support online and in-store customers."
        [[params.experience.list.items]]
        details = "Implemented token based credit card system to make the appplications PCI out-of-scope."

        [[params.experience.list]]
        title = "Information Specialist"
        dates = "2009 - 2012"
        company = "Hewlett-Packard"
        details = "Maintain HP’s Integrated Traffic Management Software (ITMS) and perform enhancements to it for use by client. ITMS is a Telecommunication software product used to capture and record real-time information from the switches.."
        [[params.experience.list.items]]
        details = "Review and validate the data models."
        [[params.experience.list.items]]
        details = "Document the Software Requirements Specifications (SRS)."

        [[params.experience.list]]
        title = "Information Analyst"
        dates = "2008 - 2009"
        company = "Hewlett-Packard"
        details = "Develop a system to integrate third party claim processing system into MetaVance. MetaVance is an Hewlett-Packard software product for the HealthCare Industry. It is used to automate core administrative processes for healthcare payers."
        [[params.experience.list.items]]
        details = "Analyze third-party claim data and creat mapping of the data to MetaVance claim format."
        [[params.experience.list.items]]
        details = "Convert existing paid and pending claims to MetaVance."

        [[params.experience.list]]
        title = "Back-end developer"
        dates = "2000 - 2008"
        company = "Hewlett-Packard"
        details = "Development and support for the Order management application software, IntradaPro. IntradaPro is a Hewlett-Packard developed JAVA based client-server application that is used for provisioning of local business orders. Involved in the analysis, design and development of various products for the application. On-call support for the Event Processing System (EPS) billing system."
        [[params.experience.list.items]]
        details = "Subject Matter Expert (SME) for the Bill Day Processing software."
        [[params.experience.list.items]]
        details = "Core design team member."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "1997 - 2000"
        company = "MASTECH Corporation"
        details = "Designed and developed a claims processing and reporting software for Blue Cross of Massachusetts."

        [[params.experience.list]]
        title = "Software Developer"
        dates = "1996 - 1997"
        company = "British-Telecom"
        details = "Maintain and enhance the bill printing software. Developed the Outward Call Barring (OCB) functionality to the billing software."

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Interests"
        details = "Chess, Skiing, Swimming, Gardening, Photography"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/sharadvernekar"
        title = "sharadvernekar"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/sharadvernekar"
        title = "sharadvernekar"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"





